feat: add postal read consumer
Informatievlaanderen/streetname-registry pull request #323
Opened 2023-10-09 09:15 UTC by pgallik

2023-10-09 13:26 UTC, jvandaal commented on .github/workflows/release.yml
> +    name: Build Snapshot Verifier
Name is still Snapshot Verifier

2023-10-09 13:26 UTC, jvandaal commented on .github/workflows/release.yml
> +      build-project: StreetNameRegistry.Snapshot.Verifier
Project is also still targetting Snapshot Verifier

2023-10-09 13:27 UTC, ArneD requested changes

2023-10-09 13:27 UTC, ArneD commented on src/StreetNameRegistry.Consumer.Read.Postal/appsettings.json
> +    "ServiceName": "streetname-registry-consumer-read-Postal-dev"
lowercase `P`

2023-10-09 13:27 UTC, ArneD commented on src/StreetNameRegistry.Consumer.Read.Postal/init.sh
> +CONTAINERID=$(curl -s http://169.254.170.2/v2/metadata | jq -r ".Containers[] | select(.Labels[\"com.amazonaws.ecs.container-name\"] | startswith(\"basisregisters-\") and endswith(\"-consumer-read-Po
lowercase `Postal`

2023-10-09 13:27 UTC, ArneD commented on src/StreetNameRegistry.Consumer.Read.Postal/StreetNameRegistry.Consumer.Read.Postal.csproj
> +  </ItemGroup>
Not needed

2023-10-09 13:27 UTC, ArneD commented on src/StreetNameRegistry.Api.Legacy/StreetName/Query/StreetNameListQueryV2.cs
> +        private readonly ConsumerPostalContext _PostalContext;
lowercase `P`

2023-10-09 13:28 UTC, jvandaal commented on src/StreetNameRegistry.Api.Legacy/StreetName/Query/StreetNameListQueryV2.cs
> +            _PostalContext = postalContext;
small caps _P

2023-10-09 13:35 UTC, jvandaal commented on src/StreetNameRegistry.Api.Legacy/StreetName/Query/StreetNameListQuery.cs
> +            if (filtering.Filter.PostalCode is not null)
!string.IsNotNullOrWhitespace?

2023-10-09 13:35 UTC, jvandaal commented on src/StreetNameRegistry.Api.Legacy/StreetName/Query/StreetNameListQueryV2.cs
> +            if (filtering.Filter.PostalCode is not null)
!string.IsNotNullOrWhitespace?

2023-10-09 14:09 UTC, emalfroy approved these changes, later dismissed

2023-10-09 14:20 UTC, ArneD requested changes

2023-10-09 14:20 UTC, ArneD commented on .github/workflows/release.yml
> +          , 'streetname-registry-consumer-read-postal'
remove from deploy, until it's configured by AWS

2023-10-09 14:20 UTC, ArneD commented on src/StreetNameRegistry.Api.Legacy/StreetName/List/ListHandler.cs
> +        private readonly ConsumerPostalContext _PostalContext;
lowercase `P`

2023-10-09 14:20 UTC, ArneD commented on src/StreetNameRegistry.Api.Legacy/StreetName/Query/StreetNameListQuery.cs
> +                }
```
else 
{
// return empty
}
```

2023-10-09 14:20 UTC, ArneD commented on src/StreetNameRegistry.Api.Legacy/StreetName/Query/StreetNameListQueryV2.cs
> +                }
else here too

2023-10-09 14:20 UTC, ArneD commented on src/StreetNameRegistry.Api.Oslo/StreetName/Query/StreetNameListOsloQuery.cs
> +                }
else

2023-10-09 14:20 UTC, ArneD commented on src/StreetNameRegistry.Api.Oslo/StreetName/Query/StreetNameListOsloQueryV2.cs
> +                }
else

2023-10-09 14:20 UTC, ArneD commented on src/StreetNameRegistry.Consumer.Read.Postal/PostalConsumerItem.cs
> +        public string? NameEnglish { get; set; }
What with multiple names?
https://api.prd.basisregisters.vlaanderen.be/v1/postinfo/8200

2023-10-09 15:39 UTC, ArneD requested changes
still in deploy steps

2023-10-10 09:42 UTC, ArneD approved these changes

2023-10-10 09:47 UTC, merged

2023-11-01 15:29 UTC, basisregisters-vlaanderen commented
:tada: This PR is included in version 3.34.0 :tada:

The release is available on [GitHub release](https://github.com/Informatievlaanderen/streetname-registry/releases/tag/v3.34.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: