feat: add ldes
Informatievlaanderen/streetname-registry pull request #48
Opened 2022-10-13 13:08 UTC by pgallik

2022-10-14 13:07 UTC, ArneD commented on .github/workflows/release.yml
> +        services: ['streetname-registry-api', 'streetname-registry-projections', 'streetname-registry-backoffice-api', 'streetname-registry-consumer', 'streetname-registry-producer', 'streetname-regi
Should be added to test: line #994

2022-10-14 13:13 UTC, ArneD requested changes

2022-10-14 13:13 UTC, ArneD commented on src/StreetNameRegistry.Producer.Snapshot.Oslo/Dockerfile
> +EXPOSE 4014/tcp
wasn't it 4016?

2022-10-18 06:34 UTC, pgallik commented on src/StreetNameRegistry.Producer.Snapshot.Oslo/Dockerfile
> +EXPOSE 4014/tcp
yes

2022-10-18 07:32 UTC, jvandaal commented on src/StreetNameRegistry.Producer.Snapshot.Oslo/Extensions/MessageExtensions.cs
> +    public static class MessageExtensions
This file can go?

2022-10-18 07:37 UTC, jvandaal commented on src/StreetNameRegistry.Producer.Snapshot.Oslo/Infrastructure/SnapshotManager.cs
> +            return eventTimestamp == snapshotVersion
Why don't we use <= ?

2022-10-18 07:41 UTC, jvandaal commented on src/StreetNameRegistry.Producer.Snapshot.Oslo/Infrastructure/Startup.cs
> +        private static string GetApiLeadingText(ApiVersionDescription description)
Text should be adjusted with the correct producer name.

2022-10-18 07:43 UTC, jvandaal commented on src/StreetNameRegistry.Producer.Snapshot.Oslo/Projections/ProjectionsController.cs
> +            RegisterConnectionString(Schema.Producer, configuration.GetConnectionString("ProducerProjections"));
Schema should change?

2022-10-18 07:58 UTC, pgallik commented on src/StreetNameRegistry.Producer.Snapshot.Oslo/Extensions/MessageExtensions.cs
> +    public static class MessageExtensions
yes

2022-10-18 14:52 UTC, jvandaal approved these changes

2022-10-18 15:36 UTC, ArneD commented on src/StreetNameRegistry.Producer.Snapshot.Oslo/Infrastructure/PublicApiHttpProxy.cs
> +    public class PublicApiHttpProxy : IPublicApiHttpProxy
Let's seal this class

2022-10-18 15:36 UTC, ArneD commented on src/StreetNameRegistry.Producer.Snapshot.Oslo/Infrastructure/Program.cs
> +    public class Program
Seal this

2022-10-18 15:42 UTC, ArneD requested changes

2022-10-18 15:42 UTC, ArneD commented on src/StreetNameRegistry.Producer.Snapshot.Oslo/Infrastructure/Configuration/AddNoCacheHeadersMiddleware.cs
> +    public class AddNoCacheHeadersMiddleware
seal this

2022-10-18 15:42 UTC, ArneD commented on src/StreetNameRegistry.Producer.Snapshot.Oslo/Infrastructure/SnapshotManager.cs
> +    public class SnapshotManager : ISnapshotManager
seal this

2022-10-18 15:42 UTC, ArneD commented on src/StreetNameRegistry.Producer.Snapshot.Oslo/Infrastructure/StaleSnapshotException.cs
> +    public class StaleSnapshotException : Exception
Check other exceptions. Needs `[Serializable]`, sealed, ctors

2022-10-18 15:42 UTC, ArneD commented on src/StreetNameRegistry.Producer.Snapshot.Oslo/ProducerProjections.cs
> +    public class ProducerProjections : ConnectedProjection<ProducerContext>
seal this

2022-10-18 15:42 UTC, ArneD commented on src/StreetNameRegistry.Producer.Snapshot.Oslo/paket.references
> +Be.Vlaanderen.Basisregisters.Api
can you recheck the references to see if all are needed?

2022-10-18 15:42 UTC, ArneD commented on test/StreetNameRegistry.Tests/SnapshotManagerTests.cs
> +    public class SnapshotManagerTests
seal this

2022-10-18 15:42 UTC, ArneD commented on test/StreetNameRegistry.Tests/SnapshotManagerTests.cs
> +using System;
usings inside namespace

2022-10-19 08:13 UTC, merged