Wfs
Informatievlaanderen/streetname-registry pull request #485
Opened 2022-02-10 13:44 UTC by YusufMavzer

2022-02-10 15:57 UTC, ArneD requested changes
Very good so far, only 3 small remarks!

2022-02-10 15:57 UTC, ArneD commented on src/StreetNameRegistry.Projections.Wfs/StreetNameHelper/StreetNameHelperProjections.cs
> +                        When<Envelope<StreetNameWasRegistered>>(async (context, message, ct) =>
indenting

2022-02-10 15:57 UTC, ArneD commented on src/StreetNameRegistry.Projections.Wfs/StreetNameHelper/StreetNameHelperProjections.cs
> +
Don't forget our new event `WasProposedV2` :)

2022-02-11 09:30 UTC, YusufMavzer commented on paket.dependencies
> +nuget Microsoft.EntityFrameworkCore.SqlServer.NetTopologySuite 5.0.6
That right. I'll take it out

2022-02-11 09:31 UTC, YusufMavzer commented on src/StreetNameRegistry.Projections.Wfs/StreetNameHelper/StreetNameHelperProjections.cs
> +
True almost forgot

2022-02-11 15:47 UTC, merged