feat: streetname name was corrected
Informatievlaanderen/streetname-registry pull request #610
Opened 2022-08-10 13:38 UTC by emalfroy

2022-08-11 07:29 UTC, ArneD requested changes
Also include projection tests.

2022-08-11 07:29 UTC, ArneD commented on src/StreetNameRegistry/Municipality/Commands/CorrectStreetNameName.cs
> +        public PersistentLocalId PersistentLocalId { get; }
Please move as second property, also in ctor.

2022-08-11 07:29 UTC, ArneD commented on src/StreetNameRegistry/Municipality/Events/StreetNameNameWasCorrectedV2.cs
> +        public int PersistentLocalId { get; }
Please move as second property, also in ctors.

2022-08-11 07:29 UTC, ArneD commented on test/StreetNameRegistry.Tests/AggregateTests/WhenCorrectingStreetNameName/GivenMunicipality.cs
> +        public void ThenStreetNameNotFoundExceptionWasThrown()
Here you use `xxxWasThrown` and a few below as well. But beneath them there are `_ThenThrowxxx`.
Could you make it consistent and use `ThenThrows`?

2022-08-11 08:30 UTC, pgallik requested changes

2022-08-12 07:23 UTC, emalfroy commented on src/StreetNameRegistry.Api.BackOffice.Abstractions/Extensions/BackOfficeContextExtensions.cs
> +
done

2022-08-12 07:23 UTC, emalfroy commented on src/StreetNameRegistry/Municipality/Events/StreetNameNameWasCorrectedV2.cs
> +        public int PersistentLocalId { get; }
done

2022-08-12 07:23 UTC, emalfroy commented on src/StreetNameRegistry/Municipality/Municipality.cs
> +            if (!StreetNames.HasPersistentLocalId(persistentLocalId, out var streetName) || streetName is null)
done

2022-08-12 12:10 UTC, ArneD approved these changes

2022-08-12 12:11 UTC, merged